---
version: '3.8'

services:
  web:
    image: somnoynadno/debug-image:v1.0.0
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
